version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
